#!/bin/bash
DOCKER_BUILDKIT=1 docker build --tag container-metrics .
err_lvl=$?
if [ "$err_lvl" = "0" ]; then
    echo "Build was successful!"
    exit 0
else
    echo "Build failed with error code $err_lvl!"
    exit $err_lvl
fi
